#
# kpasswd_version -- extract and print the version number of kpasswd
#

proc kpasswd_version {} {
	global KPASSWD
	catch "exec ident $KPASSWD" tmp
	if [regexp {Id: kpasswd.c,v ([0-9]+\.[0-9]+)} $tmp \
		dummy version] then {
		clone_output "$KPASSWD version $version\n"
	} else {
		clone_output "$KPASSWD version <unknown>\n"
	}
}
#
# kpasswd_load -- loads the program
#
proc kpasswd_load {} {
	#
}

# kpasswd_exit -- clean up and exit
proc kpasswd_exit {} {
	#
}

#
# kpasswd_start -- start kpasswd running
#
proc kpasswd_start { args } {
	global KPASSWD
	global spawn_id

	verbose "% $KPASSWD $args" 1
	eval spawn $KPASSWD $args
}
