  MIT K4 patch10	MIT K4 PC	PROPOSED NAME	(trunc to 8.3)	old Cyg
$1     $2		$3		$4		$5		$6

@ -			-		ChangeLog	changelo
@ -			debug.c		debug_decl.c	debug_de.c
@ -			des_intn.h	des_internal.h	des_inte.h
@ -			-		doc		doc
@ -			enc.c		enc.c		enc.c
@ -			-		f_README	f_readme
@ -			-		f_cbc.c		f_cbc.c
@ -			-		f_cksum.c	f_cksum.c
@ -			-		f_ecb.c		f_ecb.c
@ -			-		f_parity.c	f_parity.c
@ -			-		f_pcbc.c	f_pcbc.c
@ -			-		f_sched.c	f_sched.c
@ -			-		f_tables.c	f_tables.c
@ -			-		f_tables.h	f_tables.h
@ -			keysched.c	key_sched.c	key_sche.c
@ -			key_test.c	key_test.c	key_test.c
@ -			-		Makefile.in	makefile.in
@ -			newrndky.c	new_rnd_key.c	new_rnd_.c
@ -			qd_cksum.c	quad_cksum.c	quad_cks.c
@ -			rand_key.c	random_key.c	random_k.c
@ -			rdpasswd.c	read_password.c	read_pas.c
@ -			-		READ_ME		read_me
@ -			-		ren.msg		ren.msg
@ -			strtokey.c	string_to_key.c	string_t.c
@ -			testit.c	testit.c	testit.c
@ -			-		unix_time.c	unix_tim.c
@ -			util.c		util.c		util.c
@ -			verify.c	verify.c	verify.c
@ -			weak_key.c	weak_key.c	weak_key.c
