#
# $Id$
#

set timeout 30

load_lib "helpers.exp"

#
# Here are the tests
#

exec rm -f /tmp/dbexport

export_win "B.25: General success" /tmp/dbexport

check_mode "B.26" /tmp/dbexport 0400

if {[catch "exec chmod 666 /tmp/dbexport" output]} {
	unresolved "B.27: can't chmod /tmp/dbexport: $output"
} else {
	export_win "prep for B.27" /tmp/dbexport
	check_mode "B.27" /tmp/dbexport 0400
	exec rm -f /tmp/dbexport
}

proc test28 {} {
	if {[catch "file stat /dev/null stats" output]} {
		unresolved "B.28: can't stat /dev/null: $output"
		return
	}
	set stats(mode) [expr $stats(mode) & 07777]
	if {$stats(mode) == [expr 0400]} {
		if {[catch "exec chmod 666 /dev/null" output]} {
			unresolved "B.28: can't chmod /dev/null: $output"
			return
		}
		set stats(mode) [expr 0666]
	}
	export_win "prep for B.28" /dev/null
	check_mode "B.28" /dev/null $stats(mode)
}
test28
