//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by D:\work\khimaira\src\ui\lang\en_us\khapp.rc
//
#define IDI_MAIN_APP                    104
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_PP_CRED                     106
#define IDD_PP_IDENT                    107
#define IDB_TK_REFRESH                  108
#define IDS_MAIN_WINDOW_TITLE           108
#define IDS_MENU_FILE                   109
#define IDB_ID                          110
#define IDS_MENU_IDENTITY               110
#define IDS_MENU_CRED                   110
#define IDB_ID_DELETE                   111
#define IDS_MENU_VIEW                   111
#define IDB_ID_NEW                      112
#define IDS_MENU_OPTIONS                112
#define IDB_ID_REFRESH                  113
#define IDS_MENU_HELP                   113
#define IDB_TK                          114
#define IDS_ACTION_PROPERTIES           114
#define IDB_TK_DELETE                   115
#define IDS_ACTION_EXIT                 115
#define IDB_TK_NEW                      116
#define IDS_ACTION_NEW_ID               116
#define IDS_CFG_ROOT_NAME               116
#define IDS_ACTION_SET_DEF_ID           117
#define IDS_ACTION_SET_SRCH_ID          118
#define IDB_VW_REFRESH_SM               118
#define IDS_ACTION_DESTROY_ID           119
#define IDR_MENU_BAR                    119
#define IDS_CFG_ROOT_TITLE              119
#define IDS_ACTION_RENEW_ID             120
#define IDS_CFG_GENERAL_SHORT           120
#define IDS_ACTION_ADD_CRED             121
#define IDB_TB_BLANK                    121
#define IDS_ACTION_NEW_CRED             121
#define IDS_ACTION_PASSWD_ID            122
#define IDS_ACTION_CHOOSE_COLS          123
#define IDB_TB_BLANK_SM                 123
#define IDS_ACTION_DEBUG_WINDOW         124
#define IDB_VW_REFRESH                  124
#define IDS_ACTION_VIEW_REFRESH         125
#define IDB_ID_DELETE_DIS               125
#define IDS_MENU_LAYOUT                 126
#define IDB_ID_DELETE_DIS_SM            126
#define IDS_MENU_TOOLBARS               127
#define IDB_ID_DELETE_SM                127
#define IDS_ACTION_LAYOUT_ID            128
#define IDB_ID_DIS                      128
#define IDS_ACTION_LAYOUT_TYPE          129
#define IDB_ID_DIS_SM                   129
#define IDS_ACTION_LAYOUT_LOC           130
#define IDB_ID_NEW_DIS                  130
#define IDS_ACTION_TB_STANDARD          131
#define IDB_ID_NEW_DIS_SM               131
#define IDS_ACTION_OPT_KHIM             132
#define IDB_ID_NEW_SM                   132
#define IDS_ACTION_OPT_INIT             133
#define IDB_ID_REFRESH_DIS              133
#define IDS_ACTION_OPT_IDENTS           133
#define IDS_ACTION_OPT_NOTIF            134
#define IDB_ID_REFRESH_SM               134
#define IDS_ACTION_HELP_CTX             135
#define IDB_ID_REFRESH_DIS_SM           135
#define IDS_ACTION_HELP_CONTENTS        136
#define IDB_TK_DELETE_DIS               136
#define IDS_ACTION_HELP_INDEX           137
#define IDB_TK_DELETE_DIS_SM            137
#define IDS_ACTION_HELP_ABOUT           138
#define IDB_TK_DELETE_SM                138
#define IDB_TK_DIS_SM                   139
#define IDS_ACTIONINFO_NEW_ID           139
#define IDS_CFG_GENERAL_LONG            139
#define IDB_TK_NEW_DIS                  140
#define IDS_SAMPLE_STRING               140
#define IDB_TK_NEW_DIS_SM               141
#define IDS_NO_CREDS                    141
#define IDB_TK_NEW_SM                   142
#define IDS_WT_INIT_CREDS               142
#define IDB_TK_REFRESH_DIS              143
#define IDS_WT_NEW_CREDS                143
#define IDB_TK_REFRESH_DIS_SM           144
#define IDS_NC_PASSWORD                 144
#define IDS_NC_IDENTITY                 144
#define IDB_TK_REFRESH_SM               145
#define IDS_NC_IDENTS                   145
#define IDB_TK_SM                       146
#define IDS_NC_CREDTEXT_ID_NONE         146
#define IDB_HELP_SM                     147
#define IDS_NC_CREDTEXT_ID_ONE          147
#define IDB_HELP                        148
#define IDS_NC_CREDTEXT_ID_MANY         148
#define IDB_LOGO_SHADE                  149
#define IDS_NC_CREDTEXT_ID_INVALID      149
#define IDI_WGT_COLLAPSE                150
#define IDS_WTPOST_INIT_CREDS           150
#define IDI_WGT_EXPAND                  151
#define IDS_WTPOST_NEW_CREDS            151
#define IDB_WDG_EXPAND                  152
#define IDS_ACTION_RENEW_CRED           152
#define IDB_WDG_COLLAPSE                153
#define IDS_ACTION_DESTROY_CRED         153
#define IDB_ID_SM                       154
#define IDS_DEFAULT_FONT                154
#define IDB_WDG_EXPAND_HI               155
#define IDS_NC_CREDTEXT_TABS            155
#define IDB_WDG_COLLAPSE_HI             156
#define IDS_NOTIFY_PREFIX               156
#define IDB_WDG_CREDTYPE                157
#define IDS_NOTIFY_READY                157
#define IDB_WDG_FLAG                    158
#define IDS_NOTIFY_ATTENTION            158
#define IDB_FLAG_WARN                   159
#define IDS_ALERT_DEFAULT               159
#define IDB_FLAG_EXPIRED                160
#define IDS_PACTION_OK                  160
#define IDB_FLAG_CRITICAL               161
#define IDS_PACTION_CANCEL              161
#define IDD_NC_PASSWORD                 162
#define IDS_PACTION_CLOSE               162
#define IDD_NC_NEWCRED                  162
#define IDD_NC_BBAR                     163
#define IDS_ALERT_NOSEL_TITLE           163
#define IDD_NC_TS                       164
#define IDS_ALERT_NOSEL                 164
#define IDI_ENABLED                     165
#define IDS_NC_CREDTEXT_ID_VALID        165
#define IDI_DISABLED                    166
#define IDS_NC_CREDTEXT_ID_UNCHECKED    166
#define IDS_PROP_COL_PROPERTY           167
#define IDS_PROP_COL_VALUE              168
#define IDI_NOTIFY_NONE                 169
#define IDS_NC_NEW_IDENT                169
#define IDI_NOTIFY_INFO                 170
#define IDS_NC_CREDTEXT_ID_CHECKING     170
#define IDI_NOTIFY_WARN                 171
#define IDS_ACTION_OPEN_APP             171
#define IDI_NOTIFY_ERROR                172
#define IDS_CTX_NEW_IDENT               172
#define IDS_CTX_NEW_CREDS               173
#define IDD_CFG_MAIN                    173
#define IDS_CTX_RENEW_CREDS             174
#define IDD_CFG_GENERIC                 174
#define IDS_CTX_PROC_NEW_IDENT          175
#define IDB_LOGO_OPAQUE                 175
#define IDS_CTX_PROC_NEW_CREDS          176
#define IDD_CFG_GENERAL                 176
#define IDS_CTX_PROC_RENEW_CREDS        177
#define IDD_CFG_IDENTITIES              177
#define IDS_ACTION_CLOSE_APP            178
#define IDD_CFG_NOTIF                   178
#define IDS_NC_FAILED_TITLE             179
#define IDD_CFG_PLUGINS                 179
#define IDS_CFG_IDENTITIES_SHORT        180
#define IDD_CFG_IDENTITY                180
#define IDS_CFG_IDENTITIES_LONG         181
#define IDI_CFG_DEFAULT                 181
#define IDS_CFG_NOTIF_SHORT             182
#define IDI_CFG_MODIFIED                182
#define IDS_CFG_NOTIF_LONG              183
#define IDI_CFG_APPLIED                 183
#define IDS_CFG_PLUGINS_SHORT           184
#define IDD_CFG_IDS_TAB                 184
#define IDS_CFG_PLUGINS_LONG            185
#define IDD_CFG_ID_TAB                  185
#define IDS_CFG_IDENTITY_SHORT          186
#define IDI_CFG_DELETED                 186
#define IDS_CFG_IDENTITY_LONG           187
#define IDI_ICON1                       187
#define IDI_ID                          187
#define IDS_CTX_DESTROY_CREDS           188
#define IDB_IMPORT_SM_DIS               188
#define IDS_WARN_EXPIRE                 189
#define IDB_IMPORT                      189
#define IDS_WARN_TITLE                  190
#define IDB_IMPORT_DIS                  190
#define IDS_ALERT_MOREINFO              191
#define IDB_IMPORT_SM                   191
#define IDS_WARN_EXPIRED                192
#define IDB_CHPW_SM                     192
#define IDS_WARN_EXPIRE_ID              193
#define IDB_CHPW                        193
#define IDS_WARN_EXPIRED_ID             194
#define IDB_CHPW_DIS                    194
#define IDS_WARN_WM_TITLE               195
#define IDB_CHPW_DIS_SM                 195
#define IDS_WARN_WM_MSG                 196
#define IDD_ABOUT                       196
#define IDS_CFG_ID_TAB_SHORT            197
#define IDB_TB_SPACE                    197
#define IDS_CFG_ID_TAB_LONG             198
#define IDS_CFG_IDS_TAB_SHORT           199
#define IDS_CFG_IDS_TAB_LONG            200
#define IDS_CFG_IDS_IDENTITY            201
#define IDS_ACTION_IMPORT               202
#define IDS_CTX_IMPORT                  203
#define IDS_CFG_PI_COL_PLUGINS          204
#define IDS_PISTATE_FAILUNK             205
#define IDS_PISTATE_FAILMAX             206
#define IDS_PISTATE_FAILREG             207
#define IDS_PISTATE_FAILDIS             208
#define IDS_PISTATE_FAILLOD             209
#define IDS_PISTATE_PLACEHOLD           210
#define IDS_PISTATE_REG                 211
#define IDS_PISTATE_HOLD                212
#define IDS_PISTATE_INIT                213
#define IDS_PISTATE_RUN                 214
#define IDS_PISTATE_EXIT                215
#define IDS_CTX_PASSWORD                216
#define IDS_WT_PASSWORD                 217
#define IDS_WTPOST_PASSWORD             218
#define IDS_CTX_PROC_PASSWORD           219
#define IDS_NC_PWD_FAILED_TITLE         220
#define IDS_CMDLINE_HELP                221
#define IDC_NC_USERNAME                 1007
#define IDC_NC_PASSWORD                 1008
#define IDC_NC_CREDTEXT_LABEL           1009
#define IDC_NC_PASSWORD_LABEL           1010
#define IDC_NC_USERNAME_LABEL           1011
#define IDC_NC_CREDTEXT                 1012
#define IDC_NC_HELP                     1017
#define IDC_NC_OPTIONS                  1019
#define IDC_PP_IDNAME                   1026
#define IDC_PP_IDDEF                    1027
#define IDC_PP_IDSEARCH                 1028
#define IDC_PP_IDSTATUS                 1029
#define IDC_PP_IDSTATUSIMG              1030
#define IDC_PP_IDVALID                  1031
#define IDC_PP_IDRENEW                  1032
#define IDC_NC_IDENTITY                 1033
#define IDC_NC_IDENTITY_LABEL           1034
#define IDC_PP_PROPLIST                 1035
#define IDC_PP_CPROPLIST                1036
#define IDC_NC_REALM                    1037
#define IDC_NC_REALM_LABEL              1038
#define IDC_NC_TPL_ROW                  1039
#define IDC_NC_TPL_PANEL                1040
#define IDC_NC_TPL_LABEL                1041
#define IDC_NC_TPL_INPUT                1042
#define IDC_NC_TPL_LABEL_LG             1043
#define IDC_NC_TPL_INPUT_LG             1044
#define IDC_NC_TPL_ROW2                 1045
#define IDC_NC_TPL_ROW_LG               1045
#define IDC_CFG_NODELIST                1045
#define IDAPPLY                         1048
#define IDC_CFG_SUMMARY                 1049
#define IDC_CFG_TITLE                   1050
#define IDC_CFG_PANE                    1051
#define IDC_NOTIF_MONITOR               1053
#define IDC_PP_DUMMY                    1054
#define IDC_NOTIF_RENEW                 1055
#define IDC_NOTIF_RENEW_THR             1056
#define IDC_NOTIF_WARN1                 1057
#define IDC_NOTIF_WARN1_THR             1058
#define IDC_NOTIF_WARN2                 1059
#define IDC_NOTIF_WARN2_THR             1060
#define IDC_CFG_KEEPRUNNING             1061
#define IDC_CFG_STARTUP_GROUP           1062
#define IDC_CFG_AUTOSTART               1063
#define IDC_CFG_AUTOIMPORT              1064
#define IDC_CFG_AUTOINIT                1065
#define IDC_CFG_OTHER                   1066
#define IDC_CFG_MONITOR                 1069
#define IDC_CFG_STICKY                  1070
#define IDC_CFG_IDENTS                  1071
#define IDC_CFG_IDENTITY                1072
#define IDC_CFG_RENEW                   1075
#define IDC_CFG_REMOVE                  1076
#define IDC_CFG_TAB                     1077
#define IDC_CFG_TARGET                  1078
#define IDC_CFG_PLUGINS                 1079
#define IDC_CFG_PLUGINGRP               1080
#define IDC_CFG_LBL_DESC                1083
#define IDC_CFG_DESC                    1084
#define IDC_CFG_LBL_STATE               1085
#define IDC_CFG_STATE                   1086
#define IDC_CFG_LBL_DEPS                1087
#define IDC_CFG_DEPS                    1088
#define IDC_CFG_DISABLE                 1089
#define IDC_CFG_ENABLE                  1090
#define IDC_CFG_PROVGRP                 1091
#define IDC_CFG_LBL_MOD                 1092
#define IDC_CFG_MODULE                  1093
#define IDC_CFG_LBL_VEN                 1094
#define IDC_CFG_VENDOR                  1095
#define IDC_CFG_REGISTER                1097
#define IDC_CFG_NETDETECT               1098
#define IDC_PP_STICKY                   1099
#define IDC_PRODUCT                     1100
#define IDC_COPYRIGHT                   1101
#define IDC_BUILDINFO                   1102
#define IDC_LIST1                       1103
#define IDC_MODULES                     1103
#define IDA_ACTIVATE_MENU               40003
#define IDA_UP                          40004
#define IDA_DOWN                        40005
#define IDA_LEFT                        40006
#define IDA_RIGHT                       40007
#define IDA_ESC                         40008
#define IDA_ENTER                       40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        198
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
