#
# import_version -- extract and print the version number of import
#

proc import_version {} {
	global IMPORT
	set tmp [exec ident $IMPORT]
	if [regexp {Header: .*import.c,v ([0-9]+\.[0-9]+)} $tmp \
		dummy version] then {
		clone_output "$IMPORT version $version\n"
	} else {
		clone_output "$IMPORT version <unknown>\n"
	}
}
#
# import_load -- loads the program
#
proc import_load {} {
	#
}

# import_exit -- clean up and exit
proc import_exit {} {
	#
}

#
# import_start -- start import running
#
proc import_start { args } {
	global IMPORT
	global spawn_id

	verbose "% $IMPORT $args" 1
	eval spawn $IMPORT $args
}
