#!/bin/sh

force=

usage="Usage: ./config.status [--recheck] [--version] [--help]"
for option
do
  case "$option" in
  --force | -f)
    echo "Remaking all configuration files"
    force=--force ;;
  -help | --help | --hel | --he | --h)
    echo "$usage"; exit 0 ;;
  *) echo "$usage"; exit 1 ;;
  esac
done

./util/autoconf/autoreconf  -m util/autoconf -l . --verbose $force 
