/*
 * lib/gssapi/krb5/gssapi_err_krb5.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_k5g_error_table (void);
#endif

#define N_(x) (x)

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	N_("Principal in credential cache does not match desired name"),
	N_("No principal in keytab matches desired name"),
	N_("Credential cache has no TGT"),
	N_("Authenticator has no subkey"),
	N_("Context is already fully established"),
	N_("Unknown signature type in token"),
	N_("Invalid field length in token"),
	N_("Attempt to use incomplete security context"),
	N_("Bad magic number for krb5_gss_ctx_id_t"),
	N_("Bad magic number for krb5_gss_cred_id_t"),
	N_("Bad magic number for krb5_gss_enc_desc"),
	N_("Sequence number in token is corrupt"),
	N_("Credential cache is empty"),
	N_("Acceptor and Initiator share no checksum types"),
	N_("Requested lucid context version not supported"),
	N_("PRF input too long"),
	N_("Bad magic number for iakerb_ctx_id_t"),
    0
};

#include <com_err.h>

const struct error_table et_k5g_error_table = { text, 39756032L, 17 };

#if !defined(_WIN32)
void initialize_k5g_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_k5g_error_table);
}
#endif
