rename	crerrep.c	cr_err_repl.c
rename	crauthre.c	cr_auth_repl.c
rename	cr_death.c	cr_death_pkt.c
rename	crticket.c	cr_tkt.c
rename	decomtkt.c	decomp_tkt.c
rename	getadtkt.c	g_ad_tkt.c
rename	getadmhs.c	g_admhst.c
rename	get_cred.c	g_cred.c
rename	getintkt.c	g_pw_in_tkt.c
rename	getkrbhs.c	g_krbhst.c
rename	getphost.c	g_phost.c
rename	getpwtkt.c	g_pw_tkt.c
rename	get_req.c	g_request.c
rename	g_svctkt.c	g_svc_in_tkt.c
rename	gettfnam.c	g_tf_fname.c
rename	gettfrlm.c	g_tf_realm.c
rename	getrealm.c	realmofhost.c
rename	k_gethst.c	gethostname.c
rename	knm_pars.c	kname_parse.c
rename	k_errtxt.c	err_txt.c
rename	k_gettkt.c	g_in_tkt.c
rename	mth_snam.c	month_sname.c
rename	pkt_ciph.c	pkt_cipher.c
rename	rdservky.c	rd_svc_key.c
rename	savecred.c	save_creds.c
rename	send_kdc.c	send_to_kdc.c
rename	s_cascmp.c	strcasecmp.c
rename	tkt_strg.c	tkt_string.c
rename	util.c	ad_print.c
