/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "iprop.h"
#pragma ident "@(#)iprop.x	1.2	04/02/20 SMI"

void *
iprop_null_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

kdb_incr_result_t *
iprop_get_updates_1_svc(kdb_last_t *argp, struct svc_req *rqstp)
{
	static kdb_incr_result_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

kdb_fullresync_result_t *
iprop_full_resync_1_svc(void *argp, struct svc_req *rqstp)
{
	static kdb_fullresync_result_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
