/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "iprop.h"
#pragma ident "@(#)iprop.x	1.2	04/02/20 SMI"


void
krb5_iprop_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *iprop_null_1_arg;
	kdb_incr_result_t  *result_2;
	kdb_last_t  iprop_get_updates_1_arg;
	kdb_fullresync_result_t  *result_3;
	char *iprop_full_resync_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, KRB5_IPROP_PROG, KRB5_IPROP_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = iprop_null_1((void*)&iprop_null_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = iprop_get_updates_1(&iprop_get_updates_1_arg, clnt);
	if (result_2 == (kdb_incr_result_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = iprop_full_resync_1((void*)&iprop_full_resync_1_arg, clnt);
	if (result_3 == (kdb_fullresync_result_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	krb5_iprop_prog_1 (host);
exit (0);
}
