load_lib "helpers.exp"

set timeout 10

server_start "U.1: -h" "-h" 0 {
	-re {Usage: .*} {}
} {
	eof {}
}
server_exit "U.1: -h" 255

server_start "U.4: -n" "-n" 1 {
	"Enter KDC database master key:" {
		myfail "unexpected password prompt"
	}
	"KADM Server starting in the OVSEC_KADM mode" {}
}

server_exit "U.4: -n" -1

server_start "U.5: no -n" "" 1 {
	"KADM Server starting in the OVSEC_KADM mode" {}
} {
	"Enter KDC database master key:" { send "mrroot\n" }
}
server_exit "U.5: no -n" -1
