#
# export_version -- extract and print the version number of export
#

proc export_version {} {
	global EXPORT
	set tmp [exec ident $EXPORT]
	if [regexp {Header: .*export.c,v ([0-9]+\.[0-9]+)} $tmp \
		dummy version] then {
		clone_output "$EXPORT version $version\n"
	} else {
		clone_output "$EXPORT version <unknown>\n"
	}
}
#
# export_load -- loads the program
#
proc export_load {} {
	#
}

# export_exit -- clean up and exit
proc export_exit {} {
	#
}

#
# export_start -- start export running
#
proc export_start { args } {
	global EXPORT
	global spawn_id

	verbose "% $EXPORT $args" 1
	eval spawn $EXPORT $args
}
