/*
 * ettmp12124.c:
 * This file is automatically generated; please do not edit it.
 */
#if defined(_WIN32)
# include "win-mac.h"
#endif

#if !defined(_WIN32)
extern void initialize_adb_error_table (void);
#endif

/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
typedef /*@null@*/ const char *ncptr;
/*@=redef@*/

static ncptr const text[] = {
	"No Error",
	"Principal or policy already exists",
	"Principal or policy does not exist",
	"Database not initialized",
	"Invalid policy name",
	"Invalid principal name",
	"Database inconsistency detected",
	"XDR encoding error",
	"Failure!",
	"Bad lock mode",
	"Cannot lock database",
	"Database not locked",
	"KADM5 administration database lock file missing",
	"Insufficient permission to lock file",
    0
};

#include <com_err.h>

const struct error_table et_adb_error_table = { text, 28810240L, 14 };

#if !defined(_WIN32)
void initialize_adb_error_table (void)
    /*@modifies internalState@*/
{
    (void) add_error_table (&et_adb_error_table);
}
#endif
