#!/bin/sh

com=`basename $0`
files=$*

if [ "$files" = "" ]; then
    echo "Usage: $com file [file2 ...]"
    exit 1
fi

for file in $files
do
    filename=`basename $file | awk -F. '{print $1}'`
    troff -C -man -Tps $filename | grops -g > $filename.ps

    pages=`grep '%%Pages\:' $filename.ps | awk '{print $2}'`
    pp=$(($pages - 1))

    echo $filename': '$pages' pages'

    if [ -e csplit ]; then
        csplit -k $filename.ps /Page:/ \{$pp\}

        counter=0

        for number in `ls xx*`
        do
            cat xx00 > $filename$counter.ps
            echo '.7 dup scale' >> $filename$counter.ps
            cat $number >> $filename$counter.ps
            if [ $counter != $pages ];
                then
                echo '%%Trailer' >> $filename$counter.ps
                echo 'end' >> $filename$counter.ps
                echo '%%EOF' >> $filename$counter.ps
            fi
            counter=$(($counter + 1))
        done

        rm $filename.ps $filename'0.ps' xx*
    else
        echo "Can't find the csplit command.  You'll have to split $filename.ps manually."
    fi
done
