KH = /mac/libraries/
KH68K = {KH}KerberosHeaders68K
KHPPC = {KH}KerberosHeadersPPC

GSSOBJSCFMPPC = "{MWPPCLibraries}ANSI C.PPC.Lib" \
	{MWPPCLibraries}MWCRuntime.Lib {MWPPCLibraries}SIOUX.PPC.Lib \
	{SharedLibraries}InterfaceLib {SharedLibraries}MathLib

OPTIONS = {INCLUDES} -enum int -opt all -strings pool -mapcr \
        -mpw_pointers -warnings off -fatext -nosyspath -maxerrors 1000 \
        -align mac68k -opt off -toc_data on -fp_contract on -sym fullpath

all : build link

libs : {KH68K} {KHPPC} {GSSOBJS68K} {GSSOBJSPPC} link

build : {KH68K} {KHPPC}
	MWC68K {OPTIONS} -prefix {KH68K} -model far {SRCS}
	MWCPPC {OPTIONS} -prefix {KHPPC} {SRCS}

.c.68K.o : .c
	MWC68K {DepDir}{Default}.c {OPTIONS} -prefix {KH68K} -model far

.c.PPC.o : .c
	MWCPPC {DepDir}{Default}.c {OPTIONS} -prefix {KHPPC}

{KH68K} : {KH}KerberosHeaders.pch {KH}KerberosHeaders.h
	MWC68K {KH}KerberosHeaders.pch -precompile {KH68K} {OPTIONS} -i {KH}

{KHPPC} : {KH}KerberosHeaders.pch {KH}KerberosHeaders.h
	MWCPPC {KH}KerberosHeaders.pch -precompile {KHPPC} {OPTIONS} -i {KH}

link :
	MWLink68K -library -model far -o libkrb5.68K {K5OBJS68K}
	MWLinkPPC -library -o libkrb5.PPC {K5OBJSPPC}
	MWLink68K -library -model far -o libgss.68K {GSSOBJS68K}
	MWLinkPPC -library -o libgss.PPC {GSSOBJSPPC}
        MWLinkPPC -sharedlibrary -name GSSLibrary -m "" \
		-@export GSSLibrary.ppc.exp -sym fullpath \
                -sharedata -map libgss.ppc.MAP -o GSSLibraryPPC \
		{GSSOBJSCFMPPC} {GSSOBJSPPC}

clean :
	Delete -i {GSSOBJS68K} {GSSOBJSPPC}
