SnapshotRoot = //GSS-Kerberos5-1.0.5

INCLUDES = {AUTOINCLUDES} -i /mac/TestTrack/

################################################################################
##
## Creating build directories
##
################################################################################

create-directories :
	If Not "`Exists -d /bin`"
		NewFolder /bin
	End
	If Not "`Exists -d /bin/68K`"
		NewFolder /bin/68K
	End
	If Not "`Exists -d /bin/PPC`"
		NewFolder /bin/PPC
	End
	If Not "`Exists -d /bin/CFM-68K`"
		NewFolder /bin/CFM-68K
	End
	
################################################################################
##
## Autogenerating classic 68K glue files
##
################################################################################

GLUE_OUTPUT = /mac/K5.CFMglue.c /mac/GSS.CFMglue.c

glue : {GLUE_OUTPUT}
glue-clean :
	Delete -i {GLUE_OUTPUT}

/mac/K5.CFMglue.c : /mac/K5.CFMglue.cin /mac/K5.CFMglue.proto.h /mac/CFMglue.c /mac/K5.moreCFMglue.cin
	perl /mac/CFMGlue.pl < /mac/K5.CFMglue.proto.h > /mac/K5.CFMglue.c
	Catenate /mac/K5.CFMglue.cin /mac/CFMglue.c /mac/K5.CFMglue.c /mac/K5.moreCFMglue.cin | Catenate > /mac/K5.CFMglue.c

/mac/GSS.CFMglue.c : /mac/GSS.CFMglue.cin /mac/GSS.CFMglue.proto.h /mac/CFMglue.c /mac/GSS.moreCFMglue.cin
	perl /mac/CFMGlue.pl < /mac/GSS.CFMglue.proto.h > /mac/GSS.CFMglue.c
	Catenate /mac/GSS.CFMglue.cin /mac/CFMglue.c /mac/GSS.CFMglue.c /mac/GSS.moreCFMglue.cin | Catenate > /mac/GSS.CFMglue.c

################################################################################
##
## Autogenerating header and source files
##
################################################################################

AUTOGEN_H_FROM_ET = /util/et/et_h.perl
AUTOGEN_C_FROM_ET = /util/et/et_c.perl

AUTOGEN_OUTPUT = 	/include/asn1_err.h /include/kdb5_err.h /include/krb5_err.h \
	/include/kv5m_err.h /include/adm_err.h \
	/lib/gssapi/generic/gssapi_err_generic.h \
	/lib/gssapi/krb5/gssapi_err_krb5.h /util/profile/prof_err.c \
	/lib/krb5/error_tables/asn1_err.c /lib/krb5/error_tables/kdb5_err.c \
	/lib/krb5/error_tables/krb5_err.c /lib/krb5/error_tables/kv5m_err.c \
	/lib/krb5/error_tables/adm_err.c /lib/gssapi/generic/gssapi_err_generic.c \
	/lib/gssapi/krb5/gssapi_err_krb5.c /util/profile/prof_err.h \
	/include/krb5.h /util/profile/profile.h \
	/include/profile.h /include/krb5/osconf.h /lib/gssapi/generic/gssapi.h \
	/include/autoconf.h

AUTOGEN_SOURCES = 	/lib/krb5/error_tables/asn1_err.et \
	/lib/krb5/error_tables/kdb5_err.et \
	/lib/krb5/error_tables/krb5_err.et \
	/lib/krb5/error_tables/kv5m_err.et \
	/lib/krb5/error_tables/adm_err.et \
	/lib/gssapi/generic/gssapi_err_generic.et \
	/lib/gssapi/krb5/gssapi_err_krb5.et \
	/util/profile/prof_err.et \
	/include/krb5.hin /util/profile/profile.hin \
	/include/krb5/stock/osconf.h /lib/gssapi/generic/gssapi.hin \
	/mac/libraries/autoconf.h

autogenerate-files : {AUTOGEN_OUTPUT}
autogenerate-clean  :
	for output_file in {AUTOGEN_OUTPUT}
		if "`Exists {output_file}`"
			SetFile -a l {output_file}
			Delete {output_file}
		end
	end

################################################################################
#
# com_err header files
#
################################################################################

/include/asn1_err.h : /lib/krb5/error_tables/asn1_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/include/asn1_err.h" < "/lib/krb5/error_tables/asn1_err.et"

/include/kdb5_err.h : /lib/krb5/error_tables/kdb5_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/include/kdb5_err.h" < "/lib/krb5/error_tables/kdb5_err.et"

/include/krb5_err.h : /lib/krb5/error_tables/krb5_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/include/krb5_err.h" < "/lib/krb5/error_tables/krb5_err.et"

/include/kv5m_err.h : /lib/krb5/error_tables/kv5m_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/include/kv5m_err.h" < "/lib/krb5/error_tables/kv5m_err.et"

/include/adm_err.h : /lib/krb5/error_tables/adm_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/include/adm_err.h" < "/lib/krb5/error_tables/adm_err.et"
	
/lib/gssapi/generic/gssapi_err_generic.h : /lib/gssapi/generic/gssapi_err_generic.et
	perl {AUTOGEN_H_FROM_ET} outfile="/lib/gssapi/generic/gssapi_err_generic.h" < "/lib/gssapi/generic/gssapi_err_generic.et"
	
/lib/gssapi/krb5/gssapi_err_krb5.h : /lib/gssapi/krb5/gssapi_err_krb5.et
	perl {AUTOGEN_H_FROM_ET} outfile="/lib/gssapi/krb5/gssapi_err_krb5.h" < "/lib/gssapi/krb5/gssapi_err_krb5.et"

/util/profile/prof_err.h : /util/profile/prof_err.et
	perl {AUTOGEN_H_FROM_ET} outfile="/util/profile/prof_err.h" < "/util/profile/prof_err.et"

################################################################################
#
# com_err source files
#
################################################################################

/lib/krb5/error_tables/asn1_err.c : /lib/krb5/error_tables/asn1_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/krb5/error_tables/asn1_err.c" < "/lib/krb5/error_tables/asn1_err.et"

/lib/krb5/error_tables/kdb5_err.c : /lib/krb5/error_tables/kdb5_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/krb5/error_tables/kdb5_err.c" < "/lib/krb5/error_tables/kdb5_err.et"

/lib/krb5/error_tables/krb5_err.c : /lib/krb5/error_tables/krb5_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/krb5/error_tables/krb5_err.c" < "/lib/krb5/error_tables/krb5_err.et"

/lib/krb5/error_tables/kv5m_err.c : /lib/krb5/error_tables/kv5m_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/krb5/error_tables/kv5m_err.c" < "/lib/krb5/error_tables/kv5m_err.et"

/lib/krb5/error_tables/adm_err.c : /lib/krb5/error_tables/adm_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/krb5/error_tables/adm_err.c" < "/lib/krb5/error_tables/adm_err.et"

/lib/gssapi/generic/gssapi_err_generic.c : /lib/gssapi/generic/gssapi_err_generic.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/gssapi/generic/gssapi_err_generic.c" < "/lib/gssapi/generic/gssapi_err_generic.et"

/lib/gssapi/krb5/gssapi_err_krb5.c : /lib/gssapi/krb5/gssapi_err_krb5.et
	perl {AUTOGEN_C_FROM_ET} outfile="/lib/gssapi/krb5/gssapi_err_krb5.c" < "/lib/gssapi/krb5/gssapi_err_krb5.et"

/util/profile/prof_err.c : /util/profile/prof_err.et
	perl {AUTOGEN_C_FROM_ET} outfile="/util/profile/prof_err.c" < "/util/profile/prof_err.et"

################################################################################
#
# other files
#
################################################################################

/include/krb5.h : /include/krb5.hin /include/krb5_err.h /include/kdb5_err.h /include/kv5m_err.h /include/asn1_err.h
	Catenate /include/krb5.hin /include/krb5_err.h /include/kdb5_err.h /include/kv5m_err.h /include/asn1_err.h > /include/krb5.h
	
/util/profile/profile.h : /util/profile/profile.hin /util/profile/prof_err.h
	Catenate /util/profile/profile.hin /util/profile/prof_err.h > /util/profile/profile.h
	
/include/profile.h : /util/profile/profile.h
	Duplicate -y /util/profile/profile.h /include/profile.h

/include/krb5/osconf.h : /include/krb5/stock/osconf.h
	Duplicate -y /include/krb5/stock/osconf.h /include/krb5/osconf.h

/lib/gssapi/generic/gssapi.h : /lib/gssapi/generic/gssapi.hin
	Duplicate -y /lib/gssapi/generic/gssapi.hin /lib/gssapi/generic/gssapi.h
	
/include/autoconf.h : /mac/libraries/autoconf.h
	Duplicate -y /mac/libraries/autoconf.h /include/autoconf.h

################################################################################
##
## Shared library specific sources (initialization and termination)
##
################################################################################

#
# GSS library
#

GSSSHLIBSRC = /mac/GSS.CFM.c
GSSSHLIBOBJ68KCFM = /bin/CFM-68K/GSS.CFM.c.CFM68.o
GSSSHLIBOBJPPC = /bin/PPC/GSS.CFM.c.PPC.o

#
# Krb5 library
#

K5SHLIBSRC = /mac/K5.CFM.c
K5SHLIBOBJ68KCFM = /bin/CFM-68K/K5.CFM.c.CFM68.o
K5SHLIBOBJPPC = /bin/PPC/K5.CFM.c.PPC.o

#
# TestTrack
#

TTSRC = /mac/TestTrack/ShlibTestTrack.c
TTOBJ68KCFM = /bin/CFM-68K/ShlibTestTrack.c.CFM68.o
TTOBJPPC = /bin/PPC/ShlibTestTrack.c.PPC.o

################################################################################
##
## Precompiled header files
##
################################################################################

KH = /mac/libraries/
KH68K = {KH}KerberosHeaders68K
KHCFM-68K = {KH}KerberosHeadersCFM-68K
KHPPC = {KH}KerberosHeadersPPC

################################################################################
##
## Runtime libraries
##
################################################################################

GSSRTLCFM68K = "/bin/MIT CLib.68K" \
	"/bin/MIT RuntimeLib.68K" \
	"{MW68KLibraries}MSL ShLibRuntimeCFM68K.Lib" \
	"{SharedLibraries}InterfaceLib" \
	"{MW68KLibraries}MathLibCFM68K (4i_8d).Lib"
GSSRTLCFMPPC = "/bin/MIT CLib.PPC" \
	"/bin/MIT RuntimeLib.PPC" \
	"{MWPPCLibraries}MSL ShLibRuntime.Lib" \
	"{SharedLibraries}InterfaceLib" \
	"{SharedLibraries}MathLib"
K5RTLCFM68K = "/bin/MIT CLib.68K" \
	"/bin/MIT RuntimeLib.68K" \
	"{MW68KLibraries}MSL ShLibRuntimeCFM68K.Lib" \
	"{SharedLibraries}InterfaceLib" \
	"{MW68KLibraries}MathLibCFM68K (4i_8d).Lib"
K5RTLCFMPPC = "/bin/MIT CLib.PPC" \
	"/bin/MIT RuntimeLib.PPC" \
	"{MWPPCLibraries}MSL ShLibRuntime.Lib" \
	"{SharedLibraries}InterfaceLib" \
	"{SharedLibraries}MathLib"
OPTIONS = {INCLUDES} -enum int -opt all -strings pool -mapcr \
        -mpw_pointers -warnings off -fatext -nosyspath -maxerrors 1000 \
        -align mac68k -opt off -toc_data on -fp_contract on -sym fullpath \
		-model farData

################################################################################
##
## General rules
##
################################################################################

all : autogenerate-files build build-gss-shlibglue build-k5-shlibglue build-testtrack link glue
libs : {KH68K} {KHPPC} {GSSOBJS68K} {GSSOBJS68KCFM} {GSSOBJSPPC} link
build : build-PPC build-68K build-68KCFM

################################################################################
##
## Compilation rules
##
################################################################################

build-68K : {GSSOBJS68K} {K5OBJS68K}
/bin/68K/ : {SRCDIRS}
.c.68K.o : .c {KH68K}
	MWC68K {OPTIONS} -o {TargDir}{Default}.c.68K.o -prefix {KH68K} -model far {DepDir}{Default}.c

build-68KCFM : {GSSOBJS68KCFM} {K5OBJS68KCFM}
/bin/CFM-68K/ : {SRCDIRS}
.c.CFM68.o : .c {KHCFM-68K}
	MWC68K {OPTIONS} -o {TargDir}{Default}.c.CFM68.o -prefix {KHCFM-68K} \
		-model cfmflat {DepDir}{Default}.c

build-PPC : {GSSOBJSPPC} {K5OBJSPPC}
/bin/PPC/ : {SRCDIRS}
.c.PPC.o : .c {KHPPC}
	MWCPPC {OPTIONS} -o {TargDir}{Default}.c.PPC.o -prefix {KHPPC} {DepDir}{Default}.c

################################################################################
##
## Shared library initialization routines and TestTrack
##
################################################################################

build-gss-shlibglue : {GSSSHLIBOBJ68KCFM} {GSSSHLIBOBJPPC}
{GSSSHLIBOBJ68KCFM} : {GSSSHLIBSRC} {KHCFM-68K}
	MWC68K {OPTIONS} -o {GSSSHLIBOBJ68KCFM} -prefix {KHCFM-68K} -model cfmflat {GSSSHLIBSRC}
{GSSSHLIBOBJPPC} : {GSSSHLIBSRC} {KHPPC}
	MWCPPC {OPTIONS} -o {GSSSHLIBOBJPPC} -prefix {KHPPC} {GSSSHLIBSRC}

build-k5-shlibglue : {K5SHLIBOBJ68KCFM} {K5SHLIBOBJPPC}
{K5SHLIBOBJ68KCFM} : {K5SHLIBSRC} {KHCFM-68K}
	MWC68K {OPTIONS} -o {K5SHLIBOBJ68KCFM} -prefix {KHCFM-68K} -model cfmflat {K5SHLIBSRC}
{K5SHLIBOBJPPC} : {K5SHLIBSRC} {KHPPC}
	MWCPPC {OPTIONS} -o {K5SHLIBOBJPPC} -prefix {KHPPC} {K5SHLIBSRC}

build-testtrack : {TTOBJ68KCFM} {TTOBJPPC}
{TTOBJ68KCFM} : {TTSRC} {KHCFM-68K}
	MWC68K {OPTIONS} -o {TTOBJ68KCFM} -prefix {KHCFM-68K} -model cfmflat {TTSRC}
{TTOBJPPC} : {TTSRC} {KHPPC}
	MWCPPC {OPTIONS} -o {TTOBJPPC} -prefix {KHPPC} {TTSRC}

################################################################################
##
## Precompiled headers
##
################################################################################
	
{KH68K} : {KH}KerberosHeaders.pch {KH}KerberosHeaders.h
	MWC68K {KH}KerberosHeaders.pch -precompile {KH68K} {OPTIONS} -i {KH}
{KHCFM-68K} : {KH}KerberosHeaders.pch {KH}KerberosHeaders.h
	MWC68K {KH}KerberosHeaders.pch -precompile {KHCFM-68K} {OPTIONS} \
		-i {KH} -model cfmflat
{KHPPC} : {KH}KerberosHeaders.pch {KH}KerberosHeaders.h
	MWCPPC {KH}KerberosHeaders.pch -precompile {KHPPC} {OPTIONS} -i {KH}

################################################################################
##
## Linking
##
################################################################################

link : link-68K link-68KCFM link-PPC link-CFMFAT

################################################################################
##
## 68 libraries
##
################################################################################

link-68K : libkrb5.68K libgss.68K

#
#	static 68K krb5 library
#

libkrb5.68K libkrb5.68K.MAP :: {AUTOGEN_OUTPUT} {K5OBJS68K}
	MWLink68K -library -model far -o libkrb5.68K {K5OBJS68K}
libkrb5.68K :: /mac/version.r
	Rez "/mac/version.r" -a -o libkrb5.68K

#
#	static GSS krb5 library
#

libgss.68K libgss.68K.MAP :: {AUTOGEN_OUTPUT} {GSSOBJS68K} 
	MWLink68K -library -model far -o libgss.68K {GSSOBJS68K}
libgss.68K :: /mac/version.r
	Rez "/mac/version.r" -a -o libgss.68K

################################################################################
##
## CFM-68K libraries
##
################################################################################

link-68KCFM : K5Library68K GSSLibrary68K

#
#	shared CFM-68K krb5 library
#
	
K5Library68K K5Library68K.MAP :: {AUTOGEN_OUTPUT} /mac/K5Library.exp {K5RTLCFM68K} {K5OBJS68KCFM} {K5SHLIBOBJ68KCFM} {TTOBJ68KCFM}
	MWLink68K -xm sharedlibrary -name K5Library -m "" \
		-model cfmflat -@export "/mac/K5Library.exp" -sym fullpath \
		-map K5Library68K.MAP -o K5Library68K \
		-init "__initializeK5" -term "__terminateK5" \
		-weakimport /mac/TestTrack/MITAthenaLib -initbefore "MIT_*TestTrackLib" \
		{K5RTLCFM68K} {K5OBJS68KCFM} {K5SHLIBOBJ68KCFM} {TTOBJ68KCFM}
K5Library68K :: /mac/version.r
	Rez "/mac/version.r" -a -o K5Library68K

#
#	shared CFM-68K GSS library
#

GSSLibrary68K GSSLibrary68K.MAP :: {AUTOGEN_OUTPUT}  K5Library68K /mac/GSSLibrary.exp {GSSRTLCFM68K} {GSSOBJS68KCFM} {GSSSHLIBOBJ68KCFM}
	MWLink68K -xm sharedlibrary -name GSSLibrary -m "" \
		-model cfmflat -@export "/mac/GSSLibrary.exp" -sym fullpath \
		-map GSSLibrary68K.MAP -o GSSLibrary68K \
		-init "__initializeGSS" -term "__terminateGSS" \
		{GSSRTLCFM68K} {GSSOBJS68KCFM} {GSSSHLIBOBJ68KCFM} K5Library68K
GSSLibrary68K :: /mac/version.r
	Rez "/mac/version.r" -a -o GSSLibrary68K

################################################################################
##
## PPC libraries
##
################################################################################

link-PPC : libkrb5.PPC K5LibraryPPC libgss.PPC GSSLibraryPPC

#
#	PPC krb5 libraries
#		static PPC krb5 library
#

libkrb5.PPC libkrb5.PPC.MAP :: {AUTOGEN_OUTPUT} {K5OBJSPPC}
	MWLinkPPC -library -o libkrb5.PPC {K5OBJSPPC}
libkrb5.PPC :: /mac/version.r
	Rez "/mac/version.r" -a -o libkrb5.PPC

#	
#		shared PPC krb5 library
#

K5LibraryPPC K5LibraryPPC.MAP :: {AUTOGEN_OUTPUT}  /mac/K5Library.exp {K5RTLCFMPPC} {K5OBJSPPC} {K5SHLIBOBJPPC} {TTOBJPPC}
	MWLinkPPC -sharedlibrary -name K5Library -m "" \
		-@export "/mac/K5Library.exp" -sym fullpath -init "__initializeK5" \
		-term "__terminateK5" \
		-weakimport /mac/TestTrack/MITAthenaLib -initbefore "MIT_*TestTrackLib" \
		-map K5LibraryPPC.MAP -o K5LibraryPPC \
		{K5RTLCFMPPC} {K5OBJSPPC} {K5SHLIBOBJPPC} {TTOBJPPC}
K5LibraryPPC :: /mac/version.r
	Rez "/mac/version.r" -a -o K5LibraryPPC

#
#	PPC GSS libraries
#

#
#		static PPC GSS library
#

libgss.PPC libgss.PPC.MAP :: {AUTOGEN_OUTPUT} {GSSOBJSPPC}
	MWLinkPPC -library -o libgss.PPC {GSSOBJSPPC}
libgss.PPC :: /mac/version.r
	Rez "/mac/version.r" -a -o libgss.PPC
#
#		shared PPC GSS library
#

GSSLibraryPPC GSSLibraryPPC.MAP :: {AUTOGEN_OUTPUT} K5LibraryPPC /mac/GSSLibrary.exp {GSSRTLCFMPPC} {GSSOBJSPPC} {GSSSHLIBOBJPPC}
	MWLinkPPC -sharedlibrary -name GSSLibrary -m "" \
		-@export "/mac/GSSLibrary.exp" -sym fullpath -init "__initializeGSS" \
		-term "__terminateGSS" -map GSSLibraryPPC.MAP -o GSSLibraryPPC \
		{GSSRTLCFMPPC} {GSSOBJSPPC} {GSSSHLIBOBJPPC} K5LibraryPPC
GSSLibraryPPC :: /mac/version.r
	Rez "/mac/version.r" -a -o GSSLibraryPPC

################################################################################
##
## Fat libraries
##
################################################################################

link-CFMFAT : GSSLib

GSSLib : GSSLibraryPPC GSSLibrary68K K5LibraryPPC K5Library68K
	Delete -i GSSLib
	Duplicate -y GSSLibraryPPC GSSLib
	MergeFragment GSSLibrary68K GSSLib
	MergeFragment K5LibraryPPC GSSLib
	MergeFragment K5Library68K GSSLib
	MergeFragment "/bin/MIT CLib.68K" GSSLib
	MergeFragment "/bin/MIT RuntimeLib.68K" GSSLib
	MergeFragment "/bin/MIT CLib.PPC" GSSLib
	MergeFragment "/bin/MIT RuntimeLib.PPC" GSSLib
	
################################################################################
##
## Clean targets
##
################################################################################

# This target punts things that get created during an MPW build

clean : autogenerate-clean glue-clean
	Delete -i {GSSOBJS68K} {GSSOBJSPPC} {GSSOBJS68KCFM} \
		{K5OBJS68K} {K5OBJSPPC} {K5OBJS68KCFM} \
		{KH68K} {KHPPC} {KHCFM-68K} \
		{GSSSHLIBOBJ68KCFM} {GSSSHLIBOBJPPC} \
		{K5SHLIBOBJ68KCFM} {K5SHLIBOBJPPC}

# This target also punts everything that gets created in other ways during normal
# build process (CW files etc)

dist-clean : clean
	Delete -i -y /bin \
		"/mac/libraries/Metrowerks/CW Pro 2/MIT C.CFM68K DLL.prj Data" \
		"/mac/libraries/Metrowerks/CW Pro 2/MIT C.PPC DLL.prj Data" \
		"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimeCFM68K DLL.prj Data" \
		"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimePPC DLL.prj Data"
	Delete -i GSSLib GSSLibraryPPC GSSLibrary68K K5LibraryPPC K5Library68K \
		GSSLibrary68K.MAP GSSLibrary68K.SYM GSSLibraryPPC.MAP GSSLibraryPPC.xSYM \
		K5Library68K.MAP K5Library68K.SYM K5LibraryPPC.MAP K5LibraryPPC.xSYM \
		libkrb5.68K libgss.68K libkrb5.PPC libgss.PPC \
		"MSL C.PPC.DLL" "MSL C.CFM68K.DLL" "MSL RuntimePPC.DLL" "MSL RuntimeCFM68K.DLL" \
		/mac/libraries/KerberosHeaders.pch.68k.o /mac/libraries/KerberosHeaders.pch.ppc.o \
		Makefile
		
################################################################################
##
## Snapshot
##
################################################################################

AUTOMACFILES = `perl "/mac/macfile_gen.pl" maclist`
AUTOMACDIRS = `perl "/mac/macfile_gen.pl" macdirs`

MACFILES = {AUTOMACFILES} {GLUE_INPUT} /Makefile.in /patchlevel.h \
	/util/et/et_h.perl /util/et/et_c.perl \
	/mac/GSS.CFM.c \
	/mac/GSSLibrary.exp \
	/mac/GSSLibrary.SAP.exp \
	/mac/K5.CFM.c \
	/mac/K5Library.exp \
	/mac/krb5.ini \
	/mac/macfile_gen.pl \
	/mac/Makefile.tmpl \
	/mac/ReadMe \
	/mac/version.r \
	/mac/kconfig/ChangeLog \
	/mac/kconfig/des_cornell.c \
	/mac/kconfig/desproto.h \
	/mac/kconfig/dnr.c \
	/mac/kconfig/encrypt.h \
	/mac/kconfig/getpasswd.c \
	/mac/kconfig/glue.h \
	/mac/kconfig/k.bw \
	/mac/kconfig/k.color \
	/mac/kconfig/kadm.c \
	/mac/kconfig/kadm.h \
	/mac/kconfig/kadm.proto.h \
	/mac/kconfig/kconfig.c \
	/mac/kconfig/kconfig.h \
	/mac/kconfig/kconfig.proto.h \
	/mac/kconfig/kconfig.r \
	/mac/kconfig/kconfig.rsrc \
	/mac/kconfig/kconfig.vers \
	/mac/kconfig/kconfig.prj \
	/mac/kconfig/kpasswd.c \
	/mac/kconfig/ldef.c \
	/mac/kconfig/MakeFile \
	/mac/kconfig/ReleaseNotes \
	/mac/kconfig/WindowUtil.c \
	/mac/kconfig/WindowUtil.h \
	/mac/kconfig/WindowUtil.proto.h \
	/mac/libraries/autoconf.h \
	/mac/libraries/ChangeLog \
	/mac/libraries/KerberosHeaders.h \
	/mac/libraries/KerberosHeaders.pch \
	/mac/libraries/KerberosHeadersCFM.pch \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT C.CFM68K DLL.prj" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT C.PPC DLL.prj" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimeCFM68K DLL.prj" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimePPC DLL.prj" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT C.CFM68K DLL.doc" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT C.PPC DLL.doc" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimeCFM68K DLL.doc" \
	"/mac/libraries/Metrowerks/CW Pro 2/MIT RuntimePPC DLL.doc" \
	/mac/TestTrack/ChangeLog \
	/mac/TestTrack/GSSforSAP.r \
	/mac/TestTrack/MITAthenaLib \
	/mac/TestTrack/ShlibTestTrack.c \
	/mac/TestTrack/ShlibTestTrack.h \
	/mac/TestTrack/TestTrackLib.h \
	/mac/TestTrack/testtrack.h \
	/mac/templatify.pl
MACDIRS = /config/ /include/ /include/krb5/ /include/krb5/stock/ \
	/include/sys/ /lib/ /lib/krb5/ /lib/gssapi/ /util/ {AUTOMACDIRS} \
	/mac/ \
	/mac/kconfig/ \
	/mac/libraries/ \
	/mac/libraries/Metrowerks/ \
	"/mac/libraries/Metrowerks/CW Pro 2/" \
	/mac/testtrack/

snapshot : autogenerate-clean
	NewFolder {SnapshotRoot}
	For SnapshotDir in {MacDirs}
		NewFolder "{SnapshotRoot}{SnapshotDir}"
		if "`Exists {TargDir}"{SnapshotDir}Makefile.in"`"
			Duplicate -y {TargDir}"{SnapshotDir}Makefile.in" {SnapshotRoot}"{SnapshotDir}Makefile.in"
			SetFile -a l {SnapshotRoot}"{SnapshotDir}Makefile.in"
		end
	end
	For SnapshotFile in {MacFiles} {Autogen_Sources}
		if "`Exists {TargDir}"{SnapshotFile}"`"
			Duplicate -y {TargDir}"{SnapshotFile}" {SnapshotRoot}"{SnapshotFile}"
			SetFile -a l {SnapshotRoot}"{SnapshotFile}"
		end
	end
	

