#ifdef UnifdefRan
/* WARNING: this file is automatically generated; do not edit! */
#endif
/*
 * $Source$
 * $Author$
 * $Id$
 *
 * Copyright 1990,1991 by the Massachusetts Institute of Technology.
 * All Rights Reserved.
 *
 * Export of this software from the United States of America is assumed
 *   to require a specific license from the United States Government.
 *   It is the responsibility of any person or organization contemplating
 *   export to obtain such a license before exporting.
 * 
 * WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
 * distribute this software and its documentation for any purpose and
 * without fee is hereby granted, provided that the above copyright
 * notice appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation, and that
 * the name of M.I.T. not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior
 * permission.  M.I.T. makes no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 * 
 *
 * Configuration definition file.
 */


#ifndef KRB5_CONFIG__
#define KRB5_CONFIG__

#ifdef HasPosixTermiosTrue
#define POSIX_TERMIOS
#endif

#ifdef HasPosixFileLocksTrue
#define POSIX_FILE_LOCKS
#endif

#ifdef HasPosixTypesTrue
#define POSIX_TYPES
#endif

#ifdef HasVoidSignalReturnTrue
#define POSIX_SIGTYPE
#define krb5_sigtype void
#else
typedef int krb5_sigtype;
#endif

#ifdef HasStringHTrue
#define USE_STRING_H
#endif

#ifndef HasStdlibHTrue
#define NO_STDLIB_H
#endif

#ifdef ForceStdlibH
#define	HAS_STDLIB_H
#endif

#ifdef HasAnsiStdio
#define	ANSI_STDIO
#endif

#ifdef ProvidePrototypes
#ifndef KRB5_PROVIDE_PROTOTYPES
#define KRB5_PROVIDE_PROTOTYPES YES
#endif
#endif

#ifdef UseNarrowPrototypes
#define NARROW_PROTOTYPES
#endif

#ifdef UseStdarg
#define	STDARG_PROTOTYPES
#endif

#ifdef NoNestedPrototypes
#define	NO_NESTED_PROTOTYPES
#endif

#ifdef UseVoid
#define HAS_VOID_TYPE
#endif

#ifdef UseConst
#define HAS_ANSI_CONST
#endif

#ifdef UseVolatile
#define HAS_ANSI_VOLATILE
#endif

#ifdef Bitsize32
#ifdef Bitsize64
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize16
 error: only one of BitsizeNN, please.
#endif
#define BITS32
#endif

#ifdef Bitsize16
#ifdef Bitsize64
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize32
 error: only one of BitsizeNN, please.
#endif
#define BITS16
#endif

#ifdef Bitsize64
#ifdef Bitsize32
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize16
 error: only one of BitsizeNN, please.
#endif
#define BITS64
#endif

#ifdef SYSV
/* Change srandom and random to use rand and srand */
/* Taken from the Sandia changes.  XXX  We should really just include */
/* srandom and random into Kerberos release, since rand() is a really */
/* bad random number generator.... [tytso:19920616.2231EDT] */
#define random() rand()
#define srandom(a) srand(a)
#ifndef unicos61
#define utimes(a,b) utime(a,b)
#endif  /* unicos61 */
#endif /* SYSV */

/* XXX these should be parameterized soon... */
#define PROVIDE_DES_CBC_CRC
#define PROVIDE_CRC32
#define PROVIDE_DES_CBC_CKSUM
#define PROVIDE_RSA_MD4
#define PROVIDE_RSA_MD5

#define DEFAULT_PWD_STRING1 "Enter password:"
#define DEFAULT_PWD_STRING2 "Re-enter password for verification:"

#define	KRB5_KDB_MAX_LIFE	(60*60*24) /* one day */
#define	KRB5_KDB_MAX_RLIFE	(60*60*24*7) /* one week */
#define	KRB5_KDB_EXPIRATION	2145830400 /* Thu Jan  1 00:00:00 2038 UTC */

#endif /* KRB5_CONFIG__ */

