#ifdef UnifdefRan
/* WARNING: this file is automatically generated; do not edit! */
#endif
/*
 * $Source$
 * $Author$
 * $Id$
 *
 * Copyright 1990,1991 by the Massachusetts Institute of Technology.
 * All Rights Reserved.
 *
 * Export of this software from the United States of America may
 *   require a specific license from the United States Government.
 *   It is the responsibility of any person or organization contemplating
 *   export to obtain such a license before exporting.
 * 
 * WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
 * distribute this software and its documentation for any purpose and
 * without fee is hereby granted, provided that the above copyright
 * notice appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation, and that
 * the name of M.I.T. not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior
 * permission.  M.I.T. makes no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 * 
 *
 * Site- and OS- dependant configuration.
 */


#ifndef KRB5_OSCONF__
#define KRB5_OSCONF__

#ifndef HasNdbmTrue
#define ODBM
#endif

#ifdef UseSysTimeH
#define	USE_SYS_TIME_H	/* Needs <sys/time.h> for time includes. */		
#endif
#ifdef UseTimeH
#define	USE_TIME_H	/* Needs <time.h> for time includes. */
#endif

#ifdef HasInetTrue
#define KRB5_USE_INET		/* Support IP address family */
#endif

#ifdef HasUnistdH
#define	HAS_UNISTD_H
#endif

#define	USE_DBM_LNAME		/* Use a DBM database for the aname/lname
				   conversion */

#define	DEFAULT_CONFIG_FILENAME	"@KRB5ROOT/krb.conf"
#define	DEFAULT_TRANS_FILENAME	"@KRB5ROOT/krb.realms"
#define	DEFAULT_LNAME_FILENAME	"@KRB5ROOT/aname"
#define	DEFAULT_KEYTAB_NAME	"FILE:@KRB5SRVTABDIR/v5srvtab"

#define DEFAULT_KDB_FILE        "@KDB5DIR/principal"
#define DEFAULT_ADMIN_ACL	"@KDB5DIR/admin_acl_file"

#define	DEFAULT_KDC_ETYPE	ETYPE_DES_CBC_CRC
#define	DEFAULT_KDC_KEYTYPE	KEYTYPE_DES
#define KDCRCACHE		"dfl:krb5kdc_rcache"

#define KDC_PORTNAME		"kerberos" /* for /etc/services or equiv. */
#define KDC_SECONDARY_PORTNAME	"kerberos-sec" /* For backwards */
					       /* compatibility with */
					       /* port 750 clients */

#define MAX_DGRAM_SIZE	4096
#define MAX_SKDC_TIMEOUT 30
#define SKDC_TIMEOUT_SHIFT 2		/* left shift of timeout for backoff */
#define SKDC_TIMEOUT_1 1		/* seconds for first timeout */

#define RCTMPDIR	"/usr/tmp"	/* directory to store replay caches */

#define KRB5_PATH_TTY	"/dev/tty"
#define KRB5_PATH_LOGIN	"@KRB5ROOT/sbin/login.krb5"
#define KRB5_PATH_RLOGIN "@KRB5ROOT/bin/rlogin"

/*
 * krb4 kadmin stuff follows
 */

/* the default syslog file */
#define KADM_SYSLOG  "@KRB5ROOT/admin_server.syslog"

/* where to find the bad password table */
#define PW_CHECK_FILE "@KRB5ROOT/bad_passwd"

#define DEFAULT_ACL_DIR	"@KDB5DIR"
#endif /* KRB5_OSCONF__ */
