//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by C:\work\pismere\athena\auth\krb5\src\windows\identity\plugins\krb5\lang\en_us\langres.rc
//
#define IDS_UNK_ADDR_FMT                101
#define IDD_NC_KRB5                     102
#define IDS_KRB5_CREDTEXT_0             102
#define IDS_KRB5_CCNAME_SHORT_DESC      103
#define IDS_KEY_ENCTYPE_SHORT_DESC      104
#define IDD_CONFIG                      104
#define IDS_TKT_ENCTYPE_SHORT_DESC      105
#define IDD_CFG_REALMS                  105
#define IDS_KEY_ENCTYPE_LONG_DESC       106
#define IDD_CFG_IDS_TAB                 106
#define IDS_TKT_ENCTYPE_LONG_DESC       107
#define IDD_PP_KRB5C                    107
#define IDS_ADDR_LIST_SHORT_DESC        108
#define IDD_PP_KRB5                     108
#define IDS_ADDR_LIST_LONG_DESC         109
#define IDD_CFG_ID_TAB                  109
#define IDS_ETYPE_NULL                  110
#define IDD_NC_KRB5_PASSWORD            110
#define IDS_ETYPE_DES_CBC_CRC           111
#define IDD_CFG_CACHES                  111
#define IDS_ETYPE_DES_CBC_MD4           112
#define IDI_PLUGIN                      112
#define IDS_ETYPE_DES_CBC_MD5           113
#define IDI_DELETED                     113
#define IDS_ETYPE_DES_CBC_RAW           114
#define IDI_NEW                         114
#define IDS_ETYPE_DES3_CBC_SHA          115
#define IDI_NORMAL                      115
#define IDS_ETYPE_DES3_CBC_RAW          116
#define IDI_MODIFIED                    116
#define IDS_ETYPE_DES_HMAC_SHA1         117
#define IDS_ETYPE_DES3_CBC_SHA1         118
#define IDS_ETYPE_AES128_CTS_HMAC_SHA1_96 119
#define IDS_ETYPE_AES256_CTS_HMAC_SHA1_96 120
#define IDS_ETYPE_ARCFOUR_HMAC          121
#define IDS_ETYPE_ARCFOUR_HMAC_EXP      122
#define IDS_ETYPE_UNKNOWN               123
#define IDS_ETYPE_LOCAL_DES3_HMAC_SHA1  124
#define IDS_ETYPE_LOCAL_RC4_MD4         125
#define IDS_KRB5_SHORT_DESC             126
#define IDS_KRB5_LONG_DESC              127
#define IDS_KRB4_SHORT_DESC             128
#define IDS_KRB4_LONG_DESC              129
#define IDS_KRB5_FLAGS_SHORT_DESC       130
#define IDS_RENEW_TILL_SHORT_DESC       131
#define IDS_RENEW_TILL_LONG_DESC        132
#define IDS_RENEW_FOR_SHORT_DESC        133
#define IDS_RENEW_FOR_LONG_DESC         134
#define IDS_KRB5_CCNAME_LONG_DESC       135
#define IDS_NC_USERNAME                 136
#define IDS_NC_REALM                    137
#define IDS_KRB5_WARNING                138
#define IDS_K5ERR_NAME_EXPIRED          139
#define IDS_K5ERR_KEY_EXPIRED           140
#define IDS_KRB5_WARN_FMT               141
#define IDS_K5ERR_FMT                   142
#define IDS_K5CFG_SHORT_DESC            143
#define IDS_K5CFG_LONG_DESC             144
#define IDS_K5RLM_SHORT_DESC            145
#define IDS_K5RLM_LONG_DESC             146
#define IDS_K5CFG_IDS_SHORT_DESC        147
#define IDS_K5CFG_IDS_LONG_DESC         148
#define IDS_K5CFG_ID_SHORT_DESC         149
#define IDS_K5CFG_ID_LONG_DESC          150
#define IDS_PLUGIN_DESC                 151
#define IDS_NC_PWD_BANNER               152
#define IDS_NC_PWD_PWD                  153
#define IDS_NC_PWD_NPWD                 154
#define IDS_NC_PWD_NPWD_AGAIN           155
#define IDS_KRB5_CREDTEXT_P0            156
#define IDS_K5CFG_IMPORT_OPTIONS        157
#define IDS_IDENTPRO_DESC               158
#define IDS_K5CCC_SHORT_DESC            159
#define IDS_K5CCC_LONG_DESC             160
#define IDS_CFG_FCTITLE                 161
#define IDS_CFG_FCN_WARNING             162
#define IDS_CFG_FCN_W_NOTFOUND          163
#define IDS_CFG_FCN_W_RELATIVE          164
#define IDS_CFG_FCOPENTITLE             165
#define IDS_UNAVAILABLE                 166
#define IDS_FLG_FORWARDABLE             167
#define IDS_FLG_FORWARDED               168
#define IDS_FLG_PROXIABLE               169
#define IDS_FLG_PROXY                   170
#define IDS_FLG_MAY_POSTDATE            171
#define IDS_FLG_POSTDATED               172
#define IDS_FLG_INVALID                 173
#define IDS_FLG_RENEWABLE               174
#define IDS_FLG_INITIAL                 175
#define IDS_FLG_PRE_AUTH                176
#define IDS_FLG_HW_AUTH                 177
#define IDS_FLG_TRANSIT_POL             178
#define IDS_FLG_OK_DELEGATE             179
#define IDS_FLG_ANONYMOUS               180
#define IDS_K5ERR_CANTWRITEPROFILE      181
#define IDS_K5ERR_PROFNOWRITE           182
#define IDS_K5ERR_PROFUSETEMP           183
#define IDS_K5ERR_PROFSUGGEST           184
#define IDS_CFG_RE_REALMS               185
#define IDS_CFG_RE_KDCS                 186
#define IDS_CFG_RE_DMAPS                187
#define IDS_CFG_RE_KDCS_R               188
#define IDS_CFG_RE_DMAPS_R              189
#define IDS_CFG_RE_HEAD_SVR             190
#define IDS_CFG_RE_HEAD_ADMIN           191
#define IDS_CFG_RE_HEAD_MASTER          192
#define IDS_CFG_RE_HEAD_DOMAIN          193
#define IDS_CFG_RE_NEWREALM             194
#define IDS_YES                         195
#define IDS_NO                          196
#define IDS_CFG_RE_NEWSERVER            197
#define IDS_CFG_RE_NEWDMAP              198
#define IDS_KRB5_NC_NAME                199
#define IDS_NCERR_IDENT_TOO_LONG        200
#define IDS_NCERR_IDENT_INVALID         201
#define IDS_NCERR_IDENT_UNKNOWN         202
#define IDS_CFG_RE_ARNUT                203
#define IDS_CFG_RE_ARNUM                204
#define IDS_CFG_RE_ASNUT                205
#define IDS_CFG_RE_ASNUM                206
#define IDS_CFG_RE_DMNUT                207
#define IDS_CFG_RE_DMNUM                208
#define IDS_CFG_RE_MNR                  209
#define IDS_CFG_RE_MDR                  210
#define IDS_CFG_RE_MNK                  211
#define IDS_CFG_RE_MDK                  212
#define IDS_CFG_RE_MAK                  213
#define IDS_CFG_RE_MMK                  214
#define IDS_CFG_RE_MND                  215
#define IDS_CFG_RE_MDD                  216
#define IDS_KVNO_SHORT_DESC             217
#define IDS_KVNO_LONG_DESC              218
#define IDC_NCK5_RENEWABLE              1002
#define IDC_NCK5_FORWARDABLE            1004
#define IDC_NCK5_REALM                  1005
#define IDC_NCK5_ADD_REALMS             1006
#define IDC_NCK5_LIFETIME_EDIT          1008
#define IDC_NCK5_RENEW_EDIT             1009
#define IDC_PPK5_CRENEW                 1014
#define IDC_PPK5_CFORWARD               1015
#define IDC_PPK5_CPROXY                 1016
#define IDC_PPK5_NAME                   1017
#define IDC_PPK5_ISSUE                  1018
#define IDC_PPK5_VALID                  1019
#define IDC_PPK5_RENEW                  1020
#define IDC_CHECK2                      1022
#define IDC_CHECK4                      1024
#define IDC_PPK5_LIFETIME               1024
#define IDC_CHECK5                      1025
#define IDC_CFG_LBL_REALM               1025
#define IDC_CFG_DEFREALM                1026
#define IDC_CFG_LBL_CFGFILE             1029
#define IDC_CFG_CFGFILE                 1030
#define IDC_CFG_WINGRP                  1031
#define IDC_LBL_IMPORT                  1032
#define IDC_CFG_IMPORT                  1033
#define IDC_CFG_LBL_HOSTNAME            1034
#define IDC_CFG_HOSTNAME                1035
#define IDC_CFG_LBL_DOMAIN              1036
#define IDC_CFG_DOMAIN                  1037
#define IDC_CFG_CREATECONFIG            1038
#define IDC_CFG_BROWSE                  1039
#define IDC_CFG_CFGFILEGRP              1040
#define IDC_CFG_CFGREALMS               1041
#define IDC_CFG_BROWSE2                 1042
#define IDC_CFG_REALMS                  1044
#define IDC_CFG_DOMAINGRP               1045
#define IDC_CFG_SERVERSGRP              1046
#define IDC_LIST3                       1047
#define IDC_CFG_KDC                     1047
#define IDC_LIST4                       1048
#define IDC_CFG_DMAP                    1048
#define IDC_CFG_LBL_DEFLIFE             1049
#define IDC_CFG_DEFLIFE                 1050
#define IDC_CFG_LBL_DEFRLIFE            1051
#define IDC_CFG_DEFRLIFE                1052
#define IDC_CFG_LIFEGRP                 1053
#define IDC_CFG_LRNG_MIN                1054
#define IDC_CFG_LRNG_MAX                1055
#define IDC_CFG_RLRNG_MIN               1056
#define IDC_CFG_RLRNG_MAX               1057
#define IDC_CFG_CCACHE                  1058
#define IDC_CFG_FCGRP                   1059
#define IDC_CFG_FCLIST                  1060
#define IDC_CFG_FCNAME                  1062
#define IDC_CFG_ADD                     1064
#define IDC_CFG_REMOVE                  1065
#define IDC_CFG_INCAPI                  1066
#define IDC_CFG_INCMSLSA                1067
#define IDC_PPK5_FLAGS                  1072
#define IDC_CFG_INCREALMS               1073
#define IDC_NCK5_ADDRESS                1074
#define IDC_IPADDRESS1                  1075
#define IDC_NCK5_PUBLICIP               1075
#define IDC_CFG_PUBLICIP                1075
#define IDC_CFG_RENEW                   1076
#define IDC_CHECK3                      1077
#define IDC_CFG_ADDRESSLESS             1077
#define IDC_CFG_FORWARD                 1078
#define IDC_CHECK1                      1079
#define ID_FOO_BAR                      40001

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
