.TH LIBICOMPAT 3 "03 Jul 1986"
.\" $Header$
.\"
.\"
.\" $Log$
.\" Revision 1.1  1994/06/10 03:27:41  eichin
.\" autoconfed isode for kerberos work
.\"
Revision 1.1  94/06/10  03:16:10  eichin
autoconfed isode for kerberos work

# Revision 1.1  1994/05/31 20:34:10  eichin
# reduced-isode release from /mit/isode/isode-subset/src
#
.\" Revision 8.0  91/07/17  12:18:01  isode
.\" Release 7.0
.\" 
.\"
.SH NAME
libicompat \- compatibility library
.SH SYNOPSIS
\fIcc\fR\0...\0\fB\-licompat\fR
.SH DESCRIPTION
The \fIlibicompat\fR library makes an attempt of providing an interface for
similar services under different operating systems.
Currently, the library works on most variants of Berkeley UNIX and AT&T UNIX.
.SH FILES
None
.SH DIAGNOSTICS
.SH AUTHOR
Marshall T. Rose
.SH BUGS
To misquote M.A.\0Padlipsky,
\*(lqsometimes when you try to make an apple look like an orange you get back
something that smells like a lemon.\*(rq
