name: Build

on:
    push: {paths: [src/**, .github/workflows/build.yml]}
    pull_request: {paths: [src/**, .github/workflows/build.yml]}

jobs:

    windows:
        runs-on: windows-latest
        env:
            KRB_INSTALL_DIR: C:\kfw
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1
            - name: Setup
              shell: cmd
              run: |
                mkdir %KRB_INSTALL_DIR%
            - uses: ilammy/msvc-dev-cmd@v1
              with:
                arch: x64
            - name: Build
              working-directory: src
              run: |
                $env:Path += ';' + $env:WindowsSdkVerBinPath + '\\x86'
                nmake -f Makefile.in prep-windows
                nmake
            - name: Populate install dir
              working-directory: src
              run: |
                nmake install
            - name: Build installer
              working-directory: src\windows\installer\wix
              run: |
                $env:Path += ';' + $env:wix + 'bin'
                nmake
