set klist $KLIST
set hostname hostname
set qualname $QUALNAME

set rm /bin/rm

if {[info commands exp_version] != {}} {
	set exp_version_4 [regexp {^4} [exp_version]]
} else {
	set exp_version_4 [regexp {^4} [expect_version]]
}

# Backward compatibility until we're using expect 5 everywhere
if {$exp_version_4} {
	global wait_error_index wait_errno_index wait_status_index
	set wait_error_index 0
	set wait_errno_index 1
	set wait_status_index 1
} else {
	set wait_error_index 2
	set wait_errno_index 3
	set wait_status_index 3
}

proc keytab_version {} {
	global KEYTAB
	puts "$KEYTAB version unknown"
}

proc keytab_load {} {
	#
}

proc keytab_exit {} {
	#
}

proc keytab_start { args } {
	global KEYTAB
	global spawn_id

	verbose "% $KEYTAB $args" 1
	eval spawn $KEYTAB $args
}


